name: Deploy CMS

on:
  workflow_dispatch:
      inputs:
        branch:
          description: 'Branch to build'
          required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: imagina/basequasar-app
          token:  ${{ secrets.DEPLOY_ADMIN_THEME }}
          ref: ${{ github.event.inputs.branch }}

      - name: Get current branch
        run: echo "Current branch is $GITHUB_REF"