name: Deploy CMS

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: IMNicolasM/basequasar-app


      - name: Set Branch to push deploy
        id: set_branch
        run: |
          if [ "${{ github.ref }}" == "refs/heads/master" ]; then
            echo "::set-output name=branch_deploy::v.8"
          else
            # Set branch_deploy to the current branch name
            echo "::set-output name=branch_deploy::${{ github.head_ref }}"
          fi


      - name: Branch
        run: | 
          git branch
          echo "${{ github.head_ref }}"
          echo "today is ${{steps.set_branch.outputs.branch_deploy}}"
