name: Deploy CMS

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get current branch
        run: echo "Current branch is ${{ github.ref.heads }}"