name: Deploy CMS

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Get current branch
        run: echo "Current branch is ${{ github.ref }}"

      - name: Action branch staging
        if: github.ref === "refs/heads/staging"
        run: echo "Current branch is github.ref"
      - name: Action branch different staging
        if: github.ref !== "refs/heads/staging"
        run: echo "Current branch is github.ref"
