name: Deploy CMS

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Action branch staging
        if: github.ref === "refs/heads/staging"
        run: echo "Current branch is ${{ steps.extract_branch.outputs.branch }}"
      - name: Action branch different staging
        if: github.ref !== "refs/heads/staging"
        run: echo "Current branch is ${{ steps.extract_branch.outputs.branch }}"
