name: Publish documentation

on: workflow_dispatch

jobs:
  copy_to_another_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish documentation to the docusaurus repository
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_DOCS_KEY }}
        with:
          source_file: 'docs/'
          destination_repo: 'imagina/docs-weygo'
          destination_branch: 'main'
          destination_folder: './docs/VueJs/'
          user_email: 'carlosdevia@imaginacolombia.com'
          user_name: 'imagina'
          commit_message: '+Added: principal Doc'
          use_rsync: true