name: Update Current Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to choose for merging with the current one?'
        type: choice
        options:
          - main
          - staging
          - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize submodules
        run: | 
          ${{ inputs.branch }}
          echo "${{ inputs.branch }}"