name: Update Current Branch

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Which branch to choose for merging with the current one?'
        type: choice
        options:
          - main
          - staging
          - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: IMNicolasM/basequasar-app
          token:  ${{ secrets.DEPLOY_ADMIN_THEME }}

      - name: Initialize submodules
        run: git submodule update --init --remote

      - name: Github Credentials
        run: |
          git config --global user.name "Imagina Actions Bot"
          git config --global user.email "carlosdevia@imaginacolombia.com"
          git config --global url."https://${{ secrets.DEPLOY_ADMIN_THEME }}@github.com/".insteadOf "https://github.com/"

      - name: Merge release to input branch
        run: |
          current_branch=$(git rev-parse --abbrev-ref HEAD)
          git checkout $current_branch
          git merge origin/${{ inputs.branch }}
          git submodule foreach --recursive git checkout $current_branch   
          git submodule foreach --recursive git merge origin/${{ inputs.branch }}
          git submodule foreach --recursive git push -u origin $current_branch
          git push origin $current_branch