name: Update Current Branch

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: IMNicolasM/basequasar-app
          token:  ${{ secrets.DEPLOY_ADMIN_THEME }}

      - name: Initialize submodules
        run: git submodule update --init --remote

      - name: Github Credentials
        run: |
          git config --global user.name "Imagina Actions Bot"
          git config --global user.email "carlosdevia@imaginacolombia.com"
          git config --global url."https://${{ secrets.DEPLOY_ADMIN_THEME }}@github.com/".insteadOf "https://github.com/"

      - name: Merge release to input branch
        run: |
          git branch
          git checkout deploy
          git merge origin/staging
          git submodule foreach --recursive git branch   
          git submodule foreach --recursive git checkout deploy   
          git submodule foreach --recursive git merge origin/staging
          git status