name: Update Current Branch

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: IMNicolasM/basequasar-app
          token:  ${{ secrets.DEPLOY_ADMIN_THEME }}

      - name: Initialize submodules
        run: git submodule update --init --remote

      - name: Github Credentials
        run: |
          git config --global user.name "Imagina Actions Bot"
          git config --global user.email "carlosdevia@imaginacolombia.com"
          git config --global url."https://${{ secrets.DEPLOY_ADMIN_THEME }}@github.com/".insteadOf "https://github.com/"

      - name: Set Branch
        id: set_branch
        run: |
          # Obtener la rama actual desde las variables de entorno de GitHub
          current_branch="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          echo "current_branch=$current_branch" >> "$GITHUB_ENV"
          
          # Establecer la rama a fusionar basándose en la rama actual
          if [ "$current_branch" == "master" ]; then
            branch_to_merge="staging"
          elif [ "$current_branch" == "staging" ]; then
            branch_to_merge="dev"
          fi
          
          # Imprimir la información de la rama a fusionar y establecerla como variable de entorno
          echo "Rama a fusionar: $current_branch -> $branch_to_merge"
          echo "branch_to_merge=$branch_to_merge" >> "$GITHUB_ENV"

      - name: Update Version
        run: |
          git remote -v
          git branch
          echo "Test: $current_branch"
          git fetch --no-recurse-submodules
          if [ "$current_branch" == "staging" ]; then
            git checkout -b $branch_to_merge
            git merge origin/$branch_to_merge
            git submodule foreach --recursive git checkout $branch_to_merge
            git submodule foreach --recursive git merge origin/$branch_to_merge
            git add .
            git commit -m "Realease"
            npm version patch
            git push origin $branch_to_merge
          fi

      - name: Merge release to input branch
        run: |
          git merge --allow-unrelated-histories origin/$branch_to_merge
          git submodule foreach --recursive git fetch
          git submodule foreach --recursive git checkout $current_branch   
          git submodule foreach --recursive git merge --allow-unrelated-histories origin/$branch_to_merge
          git submodule foreach --recursive git push -u origin $current_branch
          git push origin $current_branch

